version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - apache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  apache:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
